Hoverbear/raft-rs

- src/interchange.rs
- src/lib.rs
- src/state.rs
- tests/lib.rs
As discussed on IRC, this removes explicit node IDs and instead uses the SocketAddr of the individual cluster member.
> use SocketAddr as node id

- src/messages.capnp
- src/node.rs
- src/replica.rs
- src/store/mem.rs
- src/store/mod.rs
Testing of AppendEntries is blocked on implementing heartbeat timeouts and client requests.
> Implement Replica AppendEntries{Request, Response} handling

- Cargo.toml
- src/lib.rs
- src/messages.capnp
- src/replica.rs
- src/server.rs
- tests/hello.rs
- tests/new.rs
This commit introduces a wrapper message type, `Message`, which all
messages sent between Raft clients and servers should use to wrap the
message type.  Additionally, the client has been reduced to just the
append method. Leader refresh was removed because it's impossible to
provide correctly, and die was removed because its uneeded right now,
and in the long run shutdown should probably be provided by the server
objects, not the rpc system.
> introduce message wrapper, cleanup client

- src/lib.rs
- src/server.rs
Most uses of panicking functions (`unwrap` and `expect`) have been
removed, except in a few documented places. With this commit the story
around error handling in server.rs is complete using the following
guidelines:
* Operations that are not expected to fail should use a
call to `assert!`, `unwrap!`, `expect`, or a indexing operator.
These calls should be documented with either a comment, or
a message that will be included in the panic. Panicking in these
scenarios ensures that if program invariants are broken the
server will immediately crash instead of continuing and potentially
comprimising safety.
* Operations that may fail during normal operation (connections,
deserialization) use non-panicking error handling (`try!`, or
ignoring the failure with a warn-level log message). When an …
> remove or document all uses of unwrap in raft::Server.

- Cargo.toml
- src/connection.rs
- src/lib.rs
- src/server.rs
Stripped down #36.
Despite being a stripped down version of the above, there have still been a few more changes.
> Refactored errors with wrapped_enum and removed token from Connection

- Cargo.toml
- src/connection.rs
- src/lib.rs
- src/replica.rs
- src/server.rs
Testing logging output can be tedious... There may be mistakes with scopes.
**Note: Duplicates caused by an object being scoped multiple times is bad. Solution is to reconsider positioning - look for entry points and lift to the parent/owner if required.**
> Scoped log

- src/connection.rs
- src/server.rs
Fixes all but one of the remaining test failures under linux.  I'm still working on the last one, but it doesn't appear to be a correctness issue.  The test can safely be commented out locally until I get a real fix in.
> debug test failures under linux

- src/lib.rs
- src/replica.rs
- src/server.rs
This commits remove uses of `scoped_assert!` in tests and introduce test-specific log scopes.  See the commit messages for reasoning.
cc @james-darkfox
> change uses of  log scoping in tests

- src/lib.rs
- src/server.rs
Also renamed ErrorKind to RaftError and we're back to the exhaustive usage of `and_then`.
> Improved accept_connection and added RaftError::ConnectionRegisterFailed

- src/server.rs
Many of the server.rs tests will fail eventually if run in a loop on OSX. This
commit reduces the likelyhood of failures, but issues still remain. The
problem manifests as failed calls to `stream_shutdown` or `client_connected`.
The test may also hang indefinitely, which is a side effect of how we are
currently testing for shutdown in `stream_shutdown`.
It's unclear at this point whether this is due to misuse of the MIO APIs in
server.rs or because of a bug in MIO, or even kqueue itself.
Potentially incomplete list of tests which remain flaky after this patch:
* `test_invalid_client_message`
* `test_invalid_accept`
* `test_unreachable_peer_reconnect`
* `test_peer_accept`
> Reduce test flakiness on OSX

- .travis.yml
- README.md
- examples/register.rs
- src/client.rs
- src/messages.capnp
- src/messages.rs
- src/replica.rs
- src/state.rs
- src/state_machine/channel.rs
- src/state_machine/mod.rs
- src/state_machine/null.rs
- src/state_machine/register.rs
This is in progress but I'll keep pushing up to this branch.
Work remaining:
> Implement query and get/put for example

- src/backoff.rs
- src/client.rs
- src/consensus.rs
- src/lib.rs
- src/server.rs
- src/state.rs
`test` mods were renamed to `tests` because otherwise the `extern crate test` made it confusing.
> Initial Benchmarks

- examples/hashmap.rs
(emerged while testing hashmap example locally)
> Bugfix: CAS mode was using wrong argument for expected value.

- README.md
previously the example was missing an argument.
expanded slightly to cover the multi-node case.
> update example section

- examples/register.rs
- src/client.rs
- src/connection.rs
- src/consensus.rs
- src/messages.capnp
- src/messages.rs
- src/server.rs
via the preamble. For inbound connections, the preamble
is the authoritative source of the peer's listening address.
The information updates the `Consensus` instance as well as
the `Connection`.
relates to #92, though I wouldn't quite say "fixes" yet.
I haven't had much of my Rust reviewed, so pointers appreciated.
> peers advertise their peer address

- examples/hashmap.rs
- examples/register.rs
Allows examples to parse out hostnames such as `hoverbear.org:8080` as well.
> Examples parse hostnames

- src/consensus.rs
- src/messages.capnp
- src/messages.rs
(Closes #97, much more info there)
Steps to reproduce:
* `cd experiments/tmux/hashmap-local-3`
* `./dashboard` to get 4 tabs.
* In *Server 1* `RUST_LOG=raft::consensus=debug ./server 1`
* In *Server 2* `RUST_LOG=raft::consensus=debug ./server 2`
* In *Server 3* `RUST_LOG=raft::consensus=debug ./server 3`
* In *Command Seat* `./put foo bar` a few times (doesn't matter really)
* Look for the leader in the servers, kill it.
* Restart the leader after a moment.
* Observe looping behaivor.
This fixes is by:
* Having `append_entries` carry the entry terms as well.
* Correctly reporting back the right index.
@danburkert please review. :)
> Fix Catchup

- examples/hashmap.rs
- src/connection.rs
- src/consensus.rs
- src/lib.rs
- src/persistent_log/mem.rs
- src/persistent_log/mod.rs
- src/state.rs
for #101. @danburkert suggested that while the log interface is best driven by the first non-trivial implementations in the works, it still makes sense now to have entry() with an owned argument.
> misc cleanup

- src/consensus.rs
- src/persistent_log/mem.rs
- src/state.rs
guard against reordering of append_entries [as seen here](https://colin-scott.github.io/blog/2015/10/07/fuzzing-raft-for-fun-and-profit/)
the resulting logic is more involved, but it beats playing fast and loose (we shouldn't be seeing such reorderings in practice, but I couldn't swear on that).
> guard against message reordering

- Cargo.toml
- examples/hashmap.rs
- examples/register.rs
The dev-dependencies were not specified and the examples and tests were
not working with the latest nightly build.
- Specify versions for dev-dependencies
- Replace serde_macros with serde_derive
- Minor changes in examples required by newer versions of serde_json and bincode
> Update dependencies to work on latest nightly

- examples/hashmap.rs
- examples/register.rs
- src/consensus.rs
- src/server.rs
I'm working on a fork of raft-rs, where I'm hoping to implement some missing raft features including persistent logs, snapshotting, and cluster reconfiguration.  
As I was getting started, I noticed that a lot of the configuration was hardcoded, and thought I'd give a shot at making it more extensible by introducing a ServerBuilder.  This way, new features can be added without constantly changing the public signature for creation.
I also tried to disentangle the server creation and event loop creation.  The envisioned interface is demoed in the example code.
Let me know if this is a direction you're interested in pursuing, or if there are any modifications you'd like to see.
> Introduce builder pattern for server initialization

- Cargo.toml
- benches/log.rs
- examples/register.rs
- src/lib.rs
- src/persistent_log/fs.rs
- src/persistent_log/mod.rs
This adds a new FsLog struct that implements `persistent_log::Log`.  The raft spec requires that certain information survive a server outage to maintain correct behavior.  The memlog only maintains correctness if all servers remain alive. This should fix that. 
I wrote some benchmarks for it as well.  See results on https://github.com/jcdyer/raft-rs/pull/1.
@arthurprs provided helpful review suggestions.
> Create a log that persists to the filesystem.
